resource.AddWorkshop( "353946381" )
util.AddNetworkString( 'MusicPlay' )
--CreateConVar( 'music_enable', '1', FCVAR_ARCHIVE, "Whether or not to enable end-round music globally." )
--CreateConVar( 'music_modifier', '100', FCVAR_ARCHIVE, "Volume at which end-round music should play." )

local songs = { }

local function AddSong( n, artist, title, filename, soundtrack )
	if not songs[n] then songs[n] = { } end
	table.insert( songs[n], { artist, title, filename, soundtrack } )
	--resource.AddSingleFile( 'sound/zeaga/' ..filename ) -- Replaced by Workshop
end

AddSong( 1,	"CroxleyMoose",					"Blasphemy on the Top Shelf",				"cm_blasphemy-on-the-top-shelf.mp3" )
--	AddSong( 1,	"CroxleyMoose",					"This Took a Turn for the Worse",			"cm_this-took-a-turn-for-the-worse.mp3" )

AddSong( 1,	"DFerociousBeast",				"Aqua",										"df_aqua.mp3" )
AddSong( 1,	"DFerociousBeast",				"Battle for the House",						"df_battle-for-the-house.mp3" )
AddSong( 1,	"DFerociousBeast",				"Bearnut",									"df_bearnut.mp3" )
AddSong( 1,	"DFerociousBeast",				"Bits and Pieces",							"df_bits-and-pieces.mp3" )
AddSong( 1,	"DFerociousBeast",				"Error",									"df_error.mp3" )
AddSong( 1,	"DFerociousBeast",				"Goodbye",									"df_goodbye.mp3" )
AddSong( 1,	"DFerociousBeast",				"Hitler Goes to the Beach",					"df_hitler-goes-to-the-beach.mp3" )
AddSong( 1,	"DFerociousBeast",				"Jontron Theme Remix",						"df_jontron-theme-remix.mp3" )
AddSong( 1,	"DFerociousBeast",				"March of Seasons",							"df_march-of-seasons.mp3" )
AddSong( 1,	"DFerociousBeast",				"Pokemon Battle Theme",						"df_pokemon-battle-theme.mp3" )
AddSong( 1,	"DFerociousBeast",				"Runka Chunk",								"df_runka-chunk.mp3" )
AddSong( 1,	"DFerociousBeast",				"Sketchy Birthday",							"df_sketchy-birthday.mp3" )
AddSong( 1,	"DFerociousBeast",				"Somber",									"df_somber.mp3" )
AddSong( 1,	"DFerociousBeast",				"Song of Storms (Chiptune)",				"df_song-of-storms-chiptune.mp3" )
AddSong( 1,	"DFerociousBeast",				"Song of Storms (Metal)",					"df_song-of-storms-metal.mp3" )
AddSong( 1,	"DFerociousBeast",				"Teeth",									"df_teeth.mp3" )

AddSong( 2,	"Glitch Mob",					"Animus Vox",								"ex_animus-vox.mp3" )
AddSong( 2,	"Chetreo ft. Game Grumps",		"Rocket Grumps",							"ex_rocket-grumps.mp3" )
AddSong( 2,	"Civilization IV",				"Baba Yetu",								"ex_baba-yetu.mp3", true )
AddSong( 2,	"Final Fantasy V",				"Battle Theme",								"ex_battle.mp3", true )
AddSong( 2,	"ORANGE CARAMEL",				"Catallena",								"ex_catallena.mp3" )
--	AddSong( 2,	"2NE1",							"Come Back Home",							"ex_come-back-home.mp3" )
AddSong( 2,	"Gorillaz",						"Dare",										"ex_dare.mp3" )
AddSong( 2,	"f(x)",							"Electric Shock",							"ex_electric-shock.mp3" )
AddSong( 2,	"BattleBlock Theater",			"Secret Stage",								"ex_emphasis-on-scat.mp3", true )
AddSong( 2,	"Savant",						"Face Off",									"ex_face-off.mp3" )
AddSong( 2, "Lipps Inc",					"Funkytown",								"ex_funkytown.mp3" )
AddSong( 2, "Imogen Heap",					"Hide and Seek",							"ex_hide-and-seek.mp3" )
--	AddSong( 3, "Avril Lavigne",				"Hello Kitty",								"ex_hello-kitty.mp3" )
AddSong( 2,	"Tobtok ft. Emil Heró",			"Higher (Oliver Nelson & Skogsrå Remix)",	"ex_higher.mp3" )
AddSong( 2,	"Tower Unite",					"Kickstarter",								"ex_kickstarter.mp3", true )
AddSong( 2,	"Sporty-O",						"Let Me Hit It",							"ex_let-me-hit-it.mp3" )
AddSong( 2,	"Final Fantasy V",				"Mambo de Chocobo",							"ex_mambo-de-chocobo.mp3", true )
AddSong( 2,	"M83",							"Midnight City",							"ex_midnight-city.mp3" )
AddSong( 2,	"Savant",						"Origin",									"ex_origin.mp3" )
AddSong( 2,	"Benny Benassi",				"Satisfaction",								"ex_satisfaction.mp3" )
AddSong( 2,	"Asian Dub Foundation",			"Siberian Slengteng",						"ex_siberian-slengteng.mp3" )
AddSong( 2,	"Alien Ant Farm",				"Smooth Criminal",							"ex_smooth_criminal.mp3" )
AddSong( 2,	"Daley Mehndi",					"Tunak Tunak Tun",							"ex_tunak-tunak-tun.mp3" )
AddSong( 2,	"Final Fantasy V",				"Victory's Fanfare",						"ex_victorys-fanfare.mp3", true )
AddSong( 2,	"Black Light Dinner Party",		"We Are Golden",							"ex_we-are-golden.mp3" )

AddSong( 1,	"Tosmatobeef",					"Blender Mixer",							"tb_blender-mixer.mp3" )
AddSong( 1,	"Tosmatobeef",					"Broken Computers",							"tb_broken-computers.mp3" )
AddSong( 1,	"Tosmatobeef",					"Et the Dirt",								"tb_et-the-dirt.mp3" )
AddSong( 1,	"Tosmatobeef",					"Feedback",									"tb_feedback.mp3" )
AddSong( 1,	"Tosmatobeef",					"Grumble",									"tb_grumble.mp3" )
AddSong( 1,	"Tosmatobeef ft. Sketch",		"It Might Be a Song",						"tb_it-might-be-a-song.mp3" )

--	AddSong( 1, "Yolahola",						"BIOS",										"yt_bios.mp3" )
--	AddSong( 1, "Yolahola",						"Fieldtrip to the Arcade",					"yt_fieldtrip.mp3" )
--	AddSong( 1, "Yolahola",						"Fighting Street",							"yt_fighting_street.mp3" )
--	AddSong( 1, "Yolahola",						"System_32",								"yt_system32.mp3" )

hook.Add( 'TTTEndRound', 'EndMusic', function( )
	--if GetConVar( 'music_enable' ):GetBool( ) then
		local song = table.Random( table.Random( songs ) )
		net.Start( 'MusicPlay' )
			net.WriteTable( song )
		net.Broadcast( )
	--end
end )